/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DuAnNhom4_view;

import DuAnNhom4_repository.PhieuHoaDon_repository;
import DuAnNhom4_service.HoaDonDatHangService;
import DuAnNhom4_service.Imp.HoaDonDatHangIplm;
import DuAnNhom4_viewmodel.vHoaDonDatHang;
import DuAnNhom4_viewmodel.vPhieuHoaDon;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TRAN VAN DUONG
 */
public class DonDatHang extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private DefaultTableModel dtm = new DefaultTableModel();
    private PhieuHoaDon_repository hd = new PhieuHoaDon_repository();

    public DonDatHang() {
        initComponents();
        tbHoaDonDatHang.setModel(dtm);
        String[] header = {"Tên sản phẩm", "Giá sản phẩm", "Kích thước", "Màu sắc", "Số lượng", "Hình Ảnh", "Tên người nhận","SĐT","Địa chỉ","Tổng tiền","Ngày đặt hàng", "Trạng Thái"};
        dtm.setColumnIdentifiers(header);
        loadData(hd.getAll());
    }
     public void loadData(List<vPhieuHoaDon> list) {
        dtm.setRowCount(0);
        for (vPhieuHoaDon vhd : list) {
            dtm.addRow(new Object[]{vhd.getTENSP(),vhd.getGIABAN(),vhd.getSIZE(),vhd.getMAUSAC(),vhd.getSoLuong(),vhd.getHINHANH(),vhd.getTENNGUOINHAN(),vhd.getSDT(),vhd.getDIACHI(),vhd.getTHANHTIEN(),vhd.getNGAYDATHANG(),vhd.getTRANGTHAI()== 1 ? "Ðã thanh toán" : ""});
        }
    }
//    public void fillTable(){
//        int row = tbHoaDonDatHang.getSelectedRow();
//        vHoaDonDatHang hd = hoaDonDatHangService.getAll().get(row);
//        txtGiaSP.setText(hd.getIDSanPham().getGiaBan() + "");
//        txtKichThuoc.setText(hd.getIDSanPham().getSize());
//        txtMauSac.setText(hd.getIDSanPham().getMauSac());
//        txtSoLuong.setText(hd.getSoLuong()+"");
//        txtTenSP.setText(hd.getIDSanPham().getTenSanPham());
//        txtTrangThai.setText(hd.getTrangThai()+"");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDonDatHang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        cbDaThanhToan = new javax.swing.JCheckBox();
        cbChuaThanhToan = new javax.swing.JCheckBox();
        btnTimKiem = new javax.swing.JButton();
        btnHuyDon = new javax.swing.JButton();

        tbHoaDonDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHoaDonDatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonDatHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoaDonDatHang);

        jLabel6.setText("Trạng thái:");

        cbDaThanhToan.setText("Đã thanh toán");

        cbChuaThanhToan.setText("Chưa thanh toán");

        btnTimKiem.setBackground(new java.awt.Color(153, 153, 153));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnHuyDon.setBackground(new java.awt.Color(153, 153, 153));
        btnHuyDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHuyDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/multiply.png"))); // NOI18N
        btnHuyDon.setText("Hủy đơn hàng");
        btnHuyDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(cbDaThanhToan)
                        .addGap(18, 18, 18)
                        .addComponent(cbChuaThanhToan)
                        .addGap(33, 33, 33)
                        .addComponent(btnTimKiem)
                        .addGap(36, 36, 36)
                        .addComponent(btnHuyDon))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDaThanhToan)
                    .addComponent(cbChuaThanhToan)
                    .addComponent(btnTimKiem)
                    .addComponent(btnHuyDon))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnHuyDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyDonActionPerformed

    private void tbHoaDonDatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonDatHangMouseClicked
        // TODO add your handling code here:
//        fillTable();
    }//GEN-LAST:event_tbHoaDonDatHangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyDon;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JCheckBox cbChuaThanhToan;
    private javax.swing.JCheckBox cbDaThanhToan;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHoaDonDatHang;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
